#=============================================================================
# basic.toml --- basic configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
# SpaceVim options {{{
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "nord"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = false
    # disable cursorline
    # enable_cursorline = false
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "slant"
    statusline_inactive_separator = "bar"
    buffer_index_type = 4
    windows_index_type = 3
    enable_statusline_mode = false
    statusline_unicode_symbols = false
    # Enable vim compatible mode, avoid changing origin vim key bindings
    # vimcompatible = true
    # default_indent = 4
    enable_debug = 1
    enable_ale = 0
    # enable_ycm = 1
    # snippet_engine = "ultisnips"
    line_on_the_fly = 0
    realtime_leader_guide = 1
    # filemanager = "defx"
    filetree_direction = "right"
    # default_custom_leader = "e"
    # enable_neomake = false
    enable_os_fileformat_icon = false
    auto_disable_touchpad = 0
    # checkinstall = false
    enable_tabline_filetype_icon = false
    search_tools = ["rg", "pt", "ack", "grep", "findstr"]
    # autocomplete_method = "coc"
    # commandline_prompt = '>'
    # guifont = 'DejaVu Sans Mono for Powerline 11'
    # guifont = 'SauceCodePro Nerd Font:h11:cANSI:qDRAFT'
    # guifont = 'Inconsolata-g for Powerline 13'
    enable_statusline_tag = false
    bootstrap_before = "myspacevim#before"
    bootstrap_after  = "myspacevim#after"
    windows_smartclose = "<esc>"
    enable_language_specific_leader = false
# }}}

# SpaceVim layer config {{{
# enable denite in nvim has an error: deoplete undefined /usr/share/dict/words. The solution's pamcan -S words
[[layers]]
    name = 'denite'
[[layers]]
    name = 'format'
[[layers]]
    name = 'git'
[[layers]]
    name = 'tools'
[[layers]]
    name = 'gtags'
    gtagslabel = 'pygments'
[[layers]]
    name = 'cscope'
[[layers]]
    name = 'VersionControl'
[[layers]]
    name = 'lang#vim'
[[layers]]
    name = 'lang#php'
[[layers]]
    name = 'lang#python'
[[layers]]
    name = 'lang#java'
[[layers]]
    name = 'lang#sh'
    bash-file-head = [
        '#!/usr/bin/env bash',
        '# Time: `strftime("%Y-%m-%d %T")`',
        ''
    ]
[[layers]]
    name = 'lang#xml'
[[layers]]
    name = 'tmux'
[[layers]]
    name = 'debug'
[[layers]]
    name = 'colorscheme'
[[layers]]
    name = 'core#statusline'
    enable = true
[[layers]]
    name = 'core#tabline'
    enable = true
[[layers]]
    name = 'autocomplete'
    auto-completion-delay = 10
    auto-completion-return-key-behavior = "smart"
    auto-completion-tab-key-behavior = "smart"
[[layers]]
    name = 'lang#markdown'
    enableWcwidth = 1
    listItemIndent = 1
[[layers]]
    name = 'shell'
    default_position = 'top'
    default_height = 30
# }}}

