#!/usr/bin/env sh
# Give dmenu list of all unicode characters to copy.
# Shows the selected character in dunst if running.

# Must have wl-clipboard-git installed to even show menu.
which wl-copy 2>&1 >/dev/null || exit

if [ -e ~/.config/fontawesome ]; then
    chosen=$(grep -v "#" -h ~/.config/emoji ~/.config/fontawesome | dmenu -i -l 20 -fn Monospace-18)
else
    chosen=$(grep -v "#" ~/.config/emoji | dmenu -i -l 20 -fn Monospace-18)
fi

[ "$chosen" != "" ] || exit

c=$(echo "$chosen" | sed "s/ .*//")
echo "$c" | tr -d '\n' | wl-copy
notify-send "'$c' copied to clipboard." &

s=$(echo "$chosen" | sed "s/.*; //" | awk '{print $1}')
echo "$s" | tr -d '\n' | wl-copy --primary
notify-send "'$s' copied to primary." &
