#!/bin/bash
function lock(){
    swaylock -f -i $HOME/.wallpaper/300-Arch.png
}

case "$1" in
    lock)
        lockwin
        ;;
    logout)
        swaymsg -q exit
        ;;
    suspend)
        lockwin && systemctl suspend
        ;;
    hibernate)
        systemctl hibernate
        ;;
    reboot)
        systemctl reboot
        ;;
    shutdown)
	systemctl poweroff
        ;;
    *)
        echo "Usage: $0 {lock|logout|suspend|hibernate|reboot|shutdown}"
        exit 2
esac

exit 0
