#!/usr/bin/env sh

# Display contents of selection via dunst if running.
# Separate script for sway.

clip=$(wl-paste)
prim=$(wl-paste --primary)

[ -n "$clip" ] && notify-send "Clipboard:" "$clip"
[ -n "$prim" ] && notify-send "Primary:" "$prim"
