#!/bin/sh

WAKEALARM=/sys/class/rtc/rtc0/wakealarm
alarm=$(cat $WAKEALARM)
now=$(date +%s)
if [ -z "$alarm" ] || [ "$now" -ge "$alarm" ]; then
    # echo "hibernate triggered"
    systemctl suspend
else
    echo "normal wakeup"
fi
echo 0 > $WAKEALARM
