#!/bin/bash

PATH="$(find $HOME/.local/bin -type l,d | cut -f2 | tr '\n' ':')$PATH"

export ANDROID_HOME="$HOME/Tools/android-sdk-linux"
export NVM_DIR="$HOME/.nvm"
export NVM_NODEJS_ORG_MIRROR=http://npm.taobao.org/mirrors/node
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

export PATH="$HOME/.yarn/bin:$HOME/.npm-packages/bin:$ANDROID_HOME/emulator:$ANDROID_HOME/platform-tools:$HOME/.local/bin:$PATH"

# keychain start
type keychain >/dev/null 2>&1 && eval "$(keychain --eval --agents ssh -Q --quiet $HOME/.ssh/id_ecdsa)"
# not systemd server must run dbus
command -v systemctl >/dev/null || eval "$(dbus-launch --sh-syntax --exit-with-session)"

sudo -n loadkeys ~/.local/share/kbd/keymaps/personal.map 2>/dev/null

if [[ -z $DISPLAY ]] && [[ $(tty) = /dev/tty1 ]]; then
  # Sway start
  # exec sway -d 2> /tmp/sway.log # sway debug
  # The first card is used for actual rendering, and display buffers are copied to the secondary cards for any displays connected to them.
  # WLR_DRM_DEVICES=/dev/dri/card0 exec sway 2>/tmp/sway.log
  export XDG_CURRENT_DESKTOP=sway

  local REPLY
  echo && echo -e "  Enter [0-1] choose your start wm:
  0. Sway
  1. Wayfire
  " && echo
  read
  case "$REPLY" in
    0)
      exec sway &> ~/.cache/sway.log
      # systemd-cat -t sway sway
      ;;
    1)
      export SWAYSOCK=/run/user/$(id -u)/wayland-0
      exec wayfire &> ~/.cache/wayfire.log
      ;;
    *)
      echo "请输入正确数字 [0-1]"
      return 2
      ;;
  esac
fi
