#!/usr/bin/env zsh
# You may need to manually set your language environment
export LANG=en_US.UTF-8
# export LANGUAGE=en_US:zh_CN
export LC_CTYPE=en_US.UTF-8
# Enable 256 color to make auto-suggestions look nice
export TERM="xterm-256color"

export ANDROID_HOME="$HOME/Tools/android-sdk-linux"
export PATH="$(du $HOME/.local/bin/* | cut -f2 | tr '\n' ':')$HOME/.npm-packages/bin:$ANDROID_HOME/emulator:$ANDROID_HOME/platform-tools:$HOME/.local/bin:$PATH"

export TERMINAL="termite"
export BROWSER="qutebrowser"
export FILE="vifm"

export NVM_DIR="$HOME/.nvm"
export NVM_NODEJS_ORG_MIRROR=http://npm.taobao.org/mirrors/node
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='nvim'
fi
