sudo -n loadkeys ~/.local/share/kbd/keymaps/personal.map 2>/dev/null

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/home/graz/Source/google-cloud-sdk/path.zsh.inc' ]; then . '/home/graz/Source/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/home/graz/Source/google-cloud-sdk/completion.zsh.inc' ]; then . '/home/graz/Source/google-cloud-sdk/completion.zsh.inc'; fi

[ -f ~/.func.zsh ] && source ~/.func.zsh

[ -f ~/.aliases ] && source ~/.aliases

if [[ -z $DISPLAY ]] && [[ $(tty) = /dev/tty1 ]]; then

  # export GTK_IM_MODULE=fcitx
  # export QT_IM_MODULE=fcitx
  # export XMODIFIERS="@im=fcitx"

  #export _JAVA_AWT_WM_NONREPARENTING=1
  # Disabling client-side Qt decorations
  #export QT_QPA_PLATFORM=wayland
  #export QT_WAYLAND_DISABLE_WINDOWDECORATION="1"
  # Blank window in Java application.

  #
  # # mpv midea and music
  # MPD daemon start (if no other user instance exists)
  [ ! -s ~/.config/mpd/pid ] && mpd 2>&1 >/dev/null &
  #
  # Sway start
  # exec sway -d 2> /tmp/sway.log # sway debug

  # The first card is used for actual rendering, and display buffers are copied to the secondary cards for any displays connected to them.
  # WLR_DRM_DEVICES=/dev/dri/card0 exec sway 2>/tmp/sway.log

  XKB_DEFAULT_LAYOUT=us exec sway 2> /tmp/sway.log

fi

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

