#!/usr/bin/env sh
#
# dependencies:
#   brightnessctl
# example:
#   brightnessctl set 5%-
#   brightnessctl set +5%
# @return {Number}: Current brightness
################################

case $BLOCK_BUTTON in
	# right click
	# set to percentage
	3) brightnessctl set 50% ;;

	# scroll up
	# raise brightness
	4) brightnessctl set +5% ;;

	# scroll down
	# lower brightness
	5) brightnessctl set 5%- ;;
esac

percent=$(brightnessctl -qm | awk -F',' '{print $4}')

perc_num=$(echo $percent | cut -d% -f1)

if [ "$perc_num" -gt "80" ]; then
  LABEL=""
elif [ "$perc_num" -lt "30" ]; then
  LABEL=""
else
  LABEL=""
fi

echo "$LABEL $percent"
