#!/usr/bin/env sh
#
# dependencies:
# - light-git
# @return {Number}: Current brightness
################################

case $BLOCK_BUTTON in
	# right click
	# set to 50%
	3) light -S 50 ;;

	# scroll up
	# raise brightness
	4) light -A 10 ;;

	# scroll down
	# lower brightness
	5) light -U 10 ;;
esac

perc_num=$(light -G | cut -d"." -f1)

if [ "$perc_num" -gt "89" ]; then
  LABEL=""
elif [ "$perc_num" -lt "31" ]; then
  LABEL=""
else
  LABEL=""
fi

echo "$LABEL$perc_num%"
