#!/usr/bin/env sh

date "+%a %d %b  %H:%M"

case $BLOCK_BUTTON in
  1) pgrep -x dunst >/dev/null && notify-send "This Month" "$(cal)" ;;
	2) swaymsg -q "exec $TERMINAL -e calcurse" ;;
	3) pgrep -x dunst >/dev/null && notify-send "📅 Time/Date Module" "<b><span color=\"green\">Usage >>></span></b>
- Left click to show cal
- Middle click opens calcurse" ;;
esac
