#!/bin/bash
# dependence for docker
command -v docker > /dev/null 2>&1  || exit 1

# check docker daemon running
docker ps >/dev/null 2>&1 || exit 2

# Number of docker containers running
count=$(docker ps -q | wc -l | sed -r 's/^0$//g')
# Recent docker container IP
recent_ip=$(docker inspect --format='{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $(docker ps -q))

case $BLOCK_BUTTON in
	1) pgrep -x dunst >/dev/null && notify-send "Show Docker IP" "$recent_ip" ;;
	3) pgrep -x dunst >/dev/null && notify-send "🐳 Docker Module" "<b><span color=\"green\">Usage >>></span></b>
- Left click: show list." ;;
esac

echo "$LABEL$count"
