#!/usr/bin/env sh

# i3blocks module for pacman upgrades.
# Displays number of upgradeable packages.
# For this to work, have a `pacman -Sy` command run in the background as a
# cronjob every so often as root. This script will then read those packages.
# When clicked, it will run an upgrade via pacman.

case $BLOCK_BUTTON in
  1) swaymsg -q "exec $TERMINAL -e popupgrade" ;;
	2) notify-check-send "📦 Upgrade module list" "$(/usr/bin/pacman -Qu)" ;;
	3) notify-check-send "📦 Upgrade module" "<b><span color=\"green\">Usage >>></span></b>
- Left click to upgrade packages
- Middle click to show upgradable packages" ;;
esac


pacman -Qu | grep -v "\[ignored\]" | wc -l | sed -e "s/^0$//g"
