#!/usr/bin/env sh

WIDTH=${WIDTH:-900}
HEIGHT=${HEIGHT:-550}
report=$HOME/.local/share/weatherreport
pic=$HOME/.local/share/weatherreport.png

location="$1"; [ -z "$location" ] || { location="$location+" && rm -f "$report" ;}

localt=$(file /etc/localtime 2>/dev/null | awk -F'/' '{print $NF}')
location=${location:-"$localt"}

getforecast() {
  ping -q -c 1 1.1.1.1 >/dev/null || exit 1
  # curl -s "wttr.in/$location" > "$report" || exit 1
  curl -s "wttr.in/${location}?format=4" > "$report" || exit 1
  curl -s "wttr.in/${location}_tpq.png --output $pic" > /dev/null || exit 1
}

text=$(awk -F':' '{print $NF}' $report)

showweather() {
  echo $text | awk '{print $1$2}'
}

full_text=$(cat $report | awk '{print "Localtion "$1"\n", $2"\n", $3"\n", $4" "$5"\n"}')

# showweather() {
  # printf "%s" "$(sed '16q;d' "$report" | grep -wo "[0-9]*%" | sort -n | sed -e '$!d' | sed -e "s/^/☔ /g" | tr -d '\n')"
  # sed '13q;d' "$report" | grep -o "m\\(-\\)*[0-9]\\+" | sort -n -t 'm' -k 2n | sed -e 1b -e '$!d' | tr '\n|m' ' ' | awk '{print " ❄️",$1 "°","🌞",$2 "°"}' ;
# }

case $BLOCK_BUTTON in
    1)
      swaymsg -q "exec yad --picture --filename=$pic \
      --width=$WIDTH --height=$HEIGHT \
	    --undecorated --fixed \
	    --close-on-unfocus --no-buttons \
	    > /dev/null" ;;
    2) getforecast && showweather ;;
    3) pgrep -x dunst >/dev/null && notify-send "🌈 Weather module" "\n\- Left click for full forecast.
- Middle click to update forecast.
- ${full_text}" ;;
esac

if [ "$(stat -c %y "$report" 2>/dev/null | awk '{print $1}')" != "$(date '+%Y-%m-%d')" ]
then
  getforecast && showweather
else
  showweather
fi
