#!/usr/bin/env sh

if [[ -z "$LOCALTION" ]] ; then
  localt=$(file /etc/localtime 2>/dev/null | awk -F'/' '{print $NF}')
  [ ! -z "$localt" ] || localt="Shanghai"
  LOCALTION="${BLOCK_INSTANCE:-$localt}"
fi

report=$HOME/.local/share/weatherreport
full_report=$HOME/.local/share/weatherreport.full

[ -z "$1" ] || { LOCALTION="$1" && rm -f "$report" "$full_report";}

getweather() {
  # curl -s "wttr.in/$LOCALTION" > "$report" || exit
  checkping || exit
  # echo "wttr.in/{$LOCALTION}?format=4"
  # exit 0
  curl -s "wttr.in/{$LOCALTION}?0qm&format=%l:+%c+%t" > "$report" || exit
  # curl -s "wttr.in/${LOCALTION}_tpq.png --output $pic" > /dev/null || exit
}

showeather() {
  text=$(awk -F':' '{print $NF}' $report)
  if [ "$text" != "" ]
  then
    res=$(echo $text | awk '{print $1$2}')
    [[ "$res" != "Unknowlocation" ]] || exit 3
    echo $res
  else
    getweather && showeather
  fi
}

showfullweather() {
  awk '{print "Localtion "$1"\n"$2" "$3}' $report
}

case $BLOCK_BUTTON in
    1)
      if [ "$(stat -c %y "$full_report" 2>/dev/null | awk '{print $1}')" != "$(date '+%Y-%m-%d')" ]
      then
        curl -s "wttr.in/{$LOCALTION}?2qnmFM" > "$full_report" || exit
      fi
      swaymsg -q "exec $TERMINAL -e \"less -S $full_report\"" ;;
    2) getweather && showeather ;;
    3)
      notify-check-send "🌅 Weather module" "<b><span color=\"green\">Usage >>></span></b>
- Left click for full forecast.
- Middle click to update forecast.
\n<b><span color=\"green\">Full Wether >>></span></b>
- $(showfullweather) " ;;
esac

if [ "$(stat -c %y "$report" 2>/dev/null | awk '{print $1}')" != "$(date '+%Y-%m-%d')" ]
then
  getweather && showeather
else
  # showfullweather
  showeather
fi
